
  class AppData {
    static const Map<String, List<String>>  lessonNames = {
    "A1": [
      "Greetings & Introductions",
      "Numbers & Counting",
      "Days of the Week",
      "Months & Dates",
      "Family Members",
      "Describing People (appearance)",
      "Colors",
      "Classroom Objects",
      "School Subjects",
      "My House / Home",
      "Rooms & Furniture",
      "Clothes & Accessories",
      "Food & Drinks",
      "In the Kitchen",
      "Animals (pets & farm)",
      "Wild Animals",
      "Fruits & Vegetables",
      "Hobbies & Free-time Activities",
      "Sports",
      "Daily Routine",
      "Telling the Time",
      "Weather & Seasons",
      "Feelings & Emotions",
      "Asking & Giving Directions",
      "Places in Town",
      "Transport",
      "Jobs & Occupations",
      "Shopping",
      "Money & Prices",
      "Phone & Technology",
      "Countries & Nationalities",
      "Languages",
      "My Body & Health",
      "At the Doctor",
      "At the Restaurant",
      "At the Supermarket",
      "At the Park",
      "Making Plans",
      "Invitations & Replies",
      "Likes & Dislikes",
      "Describing Objects",
      "Talking with friends",
      "Simple Past Actions",
      "My City / Village",
      "On Holiday / Vacations",
      "Festivals & Special Days",
      "Reading a Simple Map",
      "Public Transport",
      "Asking for Help",
      "Saying Goodbye & Good Luck"
    ], 
    "A2": [
      "Personal Information",
      "Describing Feelings & Emotions",
      "Describing Daily Routines",
      "Talking About the Past (simple past regular/irregular)",
      "Future Plans (going to, will)",
      "Describing People (character/personality)",
      "Comparing People and Things",
      "Giving Reasons (because, so)",
      "Talking About Experiences",
      "Talking About Hobbies & Interests",
      "Talking About Your Weekend",
      "Making Appointments",
      "Ordering Food & Drink",
      "Shopping for Clothes",
      "Shopping for Groceries",
      "Asking for & Giving Advice",
      "Asking for Permission",
      "Making Requests",
      "Giving & Following Instructions",
      "Describing Places (city, countryside, neighborhood)",
      "At the Hotel",
      "At the Airport",
      "At the Train Station",
      "Travel and Transport",
      "Describing Weather & Climate",
      "Talking About Your Country",
      "Festivals and Celebrations",
      "Describing Past Holidays",
      "Making Suggestions",
      "Inviting and Accepting/Refusing",
      "Health Problems & Remedies",
      "Talking About Schedules & Timetables",
      "Describing Events (parties, concerts, meetings)",
      "Explaining a Problem",
      "Describing Habits",
      "Talking About Technology (gadgets, apps, internet)",
      "Using Social Media",
      "Writing Emails and Messages",
      "Talking About Hopes and Dreams",
      "Expressing Likes, Dislikes, Preferences",
      "Agreeing and Disagreeing",
      "Expressing Opinions",
      "Describing Actions in Progress (present continuous)",
      "Making Plans for the Weekend",
      "Describing Food & Recipes",
      "Describing Films and Books",
      "Talking About the Environment",
      "Giving Directions (more complex)",
      "Public Services (post office, police, bank)",
      "Describing Accidents & Emergencies"
    ],
    "B1": [
      "Describing Life Experiences",
      "Talking About Education & Studies",
      "Discussing Work & Professions",
      "Dealing with Problems & Solutions",
      "Describing Personal Qualities",
      "Making & Justifying Choices",
      "Describing Daily & Weekly Routines",
      "Talking About News & Current Events",
      "Describing Cities & Countryside",
      "Talking About Relationships & Friendship",
      "Expressing Preferences & Reasons",
      "Making Comparisons (people, places, things)",
      "Describing Changes Over Time",
      "Giving Advice & Recommendations",
      "Describing Health & Fitness",
      "Talking About Technology & Gadgets",
      "Describing Social Media Habits",
      "Discussing Rules & Obligations",
      "Explaining Problems with Solutions",
      "Telling Stories (past experiences)",
      "Describing a Process (how to…)",
      "Giving Detailed Directions",
      "Describing Events & Festivals",
      "Discussing Hobbies & Free Time in Detail",
      "Describing Feelings in Different Situations",
      "Talking About Future Predictions",
      "Arranging & Cancelling Plans",
      "Giving Compliments & Responding",
      "Describing Food, Cooking, & Eating Out",
      "Describing Accommodation (houses, apartments)",
      "Talking About Transport & Travel Experiences",
      "Discussing Environmental Issues",
      "Expressing Hopes & Ambitions",
      "Describing Films, TV, & Books in Detail",
      "Explaining Cultural Traditions",
      "Talking About Accidents & Incidents",
      "Making and Responding to Complaints",
      "Handling Difficult Conversations",
      "Expressing Agreement & Disagreement (in detail)",
      "Discussing Success & Failure",
      "Describing Festivals from Other Countries",
      "Describing Personal Achievements",
      "Handling Emergencies (in more detail)",
      "Discussing Shopping Habits",
      "Talking About Money Management",
      "Talking About News Stories",
      "Describing Problems with Public Services",
      "Writing Formal & Informal Emails",
      "Explaining Procedures (step by step)",
      "Talking About Art, Music, & Literature",
      "Making Arrangements for Meetings"
    ],
    "B2": [
      "Debating Social Issues",
      "Expressing Opinions on Controversial Topics",
      "Discussing Globalization",
      "Analyzing News Articles",
      "Understanding Cultural Differences",
      "Exploring Stereotypes & Prejudices",
      "Talking About Advanced Technology",
      "Discussing Science and Innovation",
      "Evaluating Environmental Problems and Solutions",
      "Talking About Work-Life Balance",
      "Discussing Education Systems",
      "Describing Complex Experiences",
      "Analyzing Literature and Poetry",
      "Describing Trends and Data",
      "Expressing Regret and Hypotheticals",
      "Giving Detailed Presentations",
      "Making Formal Complaints",
      "Handling Job Interviews",
      "Writing Cover Letters and CVs",
      "Giving Critical Reviews (books, films, products)",
      "Debating Morality and Ethics",
      "Discussing Art Movements",
      "Explaining Historical Events",
      "Predicting Future Developments",
      "Discussing Immigration & Integration",
      "Expressing Emotions in Complex Situations",
      "Managing Conflict and Negotiation",
      "Describing Personal Growth and Challenges",
      "Exploring Travel and Adventure",
      "Analyzing Advertising and Media Influence",
      "Talking About Health and Wellness Trends",
      "Expressing Certainty and Doubt",
      "Describing Advanced Scientific Concepts",
      "Talking About Volunteering and Charity",
      "Exploring Business and Entrepreneurship",
      "Discussing Housing and Urban Life",
      "Debating the Impact of Social Media",
      "Handling Advanced Customer Service Situations",
      "Discussing Political Systems",
      "Describing Accidents and Emergencies in Detail",
      "Writing Reports and Proposals",
      "Giving Persuasive Speeches",
      "Discussing Relationships and Communication",
      "Explaining Legal Concepts (basic law)",
      "Exploring Fashion and Trends",
      "Discussing Economics and Finance",
      "Describing Personal Beliefs and Values",
      "Analyzing Case Studies",
      "Participating in Panel Discussions",
      "Handling Cultural Misunderstandings"
    ],
    "C1": [
      "Evaluating and Synthesizing Arguments",
      "Analyzing Satire and Irony",
      "Understanding Nuanced Tone and Register",
      "Debating Ethical Dilemmas",
      "Interpreting Literary Devices",
      "Discussing International Relations",
      "Writing Academic Essays",
      "Conducting and Presenting Research",
      "Participating in Debates and Discussions",
      "Evaluating Scientific Claims",
      "Exploring Advanced Environmental Issues",
      "Explaining Philosophical Concepts",
      "Analyzing Complex Social Problems",
      "Discussing Economic Policy",
      "Understanding Legal Documents",
      "Exploring Theories in Psychology",
      "Explaining Historical Significance",
      "Analyzing Political Discourse",
      "Writing Opinion Editorials",
      "Delivering Academic Presentations",
      "Reviewing Art, Theatre, and Performance",
      "Understanding Intercultural Communication",
      "Negotiating in Professional Contexts",
      "Resolving Workplace Conflicts",
      "Discussing Leadership and Management Styles",
      "Evaluating Business Strategies",
      "Critiquing Media and Journalism",
      "Understanding Branding and Marketing Strategies",
      "Participating in Mock Interviews",
      "Writing Grant Proposals",
      "Debating Science vs. Ethics",
      "Exploring Social Justice Issues",
      "Interpreting Data Visualizations",
      "Analyzing Global Health Challenges",
      "Understanding Urbanization Trends",
      "Discussing Future Societal Changes",
      "Managing Large-Scale Projects",
      "Writing Technical Manuals",
      "Presenting Product Pitches",
      "Evaluating Art Movements",
      "Reviewing Films and Documentaries",
      "Explaining Innovations in Technology",
      "Exploring Cognitive Science",
      "Understanding Artificial Intelligence",
      "Discussing Gender and Identity Issues",
      "Interpreting Humor in Context",
      "Facilitating Group Discussions",
      "Critiquing Academic Literature",
      "Understanding Patent and Copyright Law",
      "Discussing International Development"
    ],
    "C2": [
      "Analyzing Philosophical Texts",
      "Deconstructing Advanced Literary Works",
      "Understanding Subtle Humor and Wordplay",
      "Discussing Meta-ethics and Moral Philosophy",
      "Writing Peer-Reviewed Journal Articles",
      "Conducting Advanced Scientific Research",
      "Debating Contemporary Global Issues",
      "Evaluating Supreme Court Decisions",
      "Exploring Theories of Consciousness",
      "Participating in Panel Debates",
      "Writing Satirical Essays",
      "Exploring Existential and Absurdist Literature",
      "Explaining Quantum Physics Concepts",
      "Interpreting Advanced Data Sets",
      "Writing Film and Literature Criticism",
      "Analyzing Multimodal Texts",
      "Dissecting Political Satire",
      "Discussing Macroeconomic Theory",
      "Exploring Multiculturalism and Identity",
      "Debating Bioethics and Genetic Engineering",
      "Understanding Advanced Legal Contracts",
      "Facilitating International Negotiations",
      "Writing Grant and Fellowship Applications",
      "Creating Multimedia Presentations",
      "Synthesizing Interdisciplinary Knowledge",
      "Interpreting Historical Revisionism",
      "Debating AI and Machine Ethics",
      "Critiquing Government Policy",
      "Exploring Art Theory and Criticism",
      "Discussing Linguistic Relativity",
      "Developing Advanced Business Proposals",
      "Writing for Broadcast Media",
      "Editing Academic Publications",
      "Negotiating Intellectual Property Rights",
      "Presenting at Academic Conferences",
      "Analyzing Cinematic Techniques",
      "Interpreting Religious Texts",
      "Writing Political Commentaries",
      "Exploring Theoretical Linguistics",
      "Understanding Neurodiversity",
      "Conducting Forensic Linguistic Analysis",
      "Debating Postmodernism",
      "Comparing Legal Systems",
      "Evaluating Medical Research",
      "Discussing Urban Planning and Architecture",
      "Writing Creative Non-Fiction",
      "Developing Educational Curricula",
      "Interpreting International Law",
      "Writing Opinion Pieces for National Media",
      "Engaging in High-level Mediation"
    ]
  }; 
  }
