class AppData {
  static const Map<String, List<String>> lessonNames = {
    "A1": [
      "Greetings & Introductions",
      "Numbers & Counting",
      "Days of the Week",
      "Months & Dates",
      "Family Members",
      "Describing People (appearance)",
      "Colors",
      "Classroom Objects",
      "School Subjects",
      "My House / Home",
      "Rooms & Furniture",
      "Clothes & Accessories",
      "Food & Drinks",
      "In the Kitchen",
      "Animals (pets & farm)",
      "Wild Animals",
      "Fruits & Vegetables",
      "Body Parts",
      "Hobbies & Free-time Activities",
      "Sports",
      "Daily Routine",
      "Telling the Time",
      "Weather & Seasons",
      "Feelings & Emotions",
      "Asking & Giving Directions",
      "Places in Town",
      "Transport",
      "Jobs & Occupations",
      "Shopping",
      "Money & Prices",
      "Phone & Technology",
      "Countries & Nationalities",
      "Languages",
      "My Body & Health",
      "At the Doctor",
      "At the Restaurant",
      "At the Supermarket",
      "At the Park",
      "Making Plans",
      "Invitations & Replies",
      "Likes & Dislikes",
      "Describing Objects",
      "Talking with friends",
      "Simple Past Actions",
      "My City / Village",
      "On Holiday / Vacations",
      "Festivals & Special Days",
      "Reading a Simple Map",
      "Public Transport",
      "Asking for Help",
    ],
    "A2": [
      "Personal Information",
      "Describing Feelings & Emotions",
      "Describing Daily Routines",
      "Talking About the Past (simple past regular/irregular)",
      "Future Plans (going to, will)",
      "Describing People (character/personality)",
      "Comparing People and Things",
      "Giving Reasons (because, so)",
      "Talking About Experiences",
      "Talking About Hobbies & Interests",
      "Talking About Your Weekend",
      "Making Appointments",
      "Ordering Food & Drink",
      "Shopping for Clothes",
      "Shopping for Groceries",
      "Asking for & Giving Advice",
      "Asking for Permission",
      "Making Requests",
      "Giving & Following Instructions",
      "Describing Places (city, countryside, neighborhood)",
      "At the Hotel",
      "At the Airport",
      "At the Train Station",
      "Travel and Transport",
      "Describing Weather & Climate",
      "Talking About Your Country",
      "Festivals and Celebrations",
      "Describing Past Holidays",
      "Making Suggestions",
      "Inviting and Accepting/Refusing",
      "Health Problems & Remedies",
      "Talking About Schedules & Timetables",
      "Describing Events (parties, concerts, meetings)",
      "Explaining a Problem",
      "Describing Habits",
      "Talking About Technology (gadgets, apps, internet)",
      "Using Social Media",
      "Writing Emails and Messages",
      "Talking About Hopes and Dreams",
      "Expressing Likes, Dislikes, Preferences",
      "Agreeing and Disagreeing",
      "Expressing Opinions",
      "Describing Actions in Progress (present continuous)",
      "Making Plans for the Weekend",
      "Describing Food & Recipes",
      "Describing Films and Books",
      "Talking About the Environment",
      "Giving Directions (more complex)",
      "Public Services (post office, police, bank)",
      "Describing Accidents & Emergencies",
    ],
    "B1": [
      "Describing Life Experiences",
      "Talking About Education & Studies",
      "Discussing Work & Professions",
      "Dealing with Problems & Solutions",
      "Describing Personal Qualities",
      "Making & Justifying Choices",
      "Describing Daily & Weekly Routines",
      "Talking About News & Current Events",
      "Describing Cities & Countryside",
      "Talking About Relationships & Friendship",
      "Describing Social Media Habits",
      "Discussing Rules & Obligations",
      "Explaining Problems with Solutions",
      "Telling Stories (past experiences)",
      "Describing a Process (how to…)",
      "Giving Detailed Directions",
      "Describing Events & Festivals",
      "Discussing Hobbies & Free Time in Detail",
      "Describing Feelings in Different Situations",
      "Talking About Future Predictions",
      "Arranging & Cancelling Plans",
      "Giving Compliments & Responding",
      "Describing Food, Cooking, & Eating Out",
      "Describing Accommodation (houses, apartments)",
      "Talking About Transport & Travel Experiences",
      "Discussing Environmental Issues",
      "Expressing Hopes & Ambitions",
      "Describing Films, TV, & Books in Detail",
      "Explaining Cultural Traditions",
      "Talking About Accidents & Incidents",
      "Making and Responding to Complaints",
      "Handling Difficult Conversations",
      "Expressing Agreement & Disagreement (in detail)",
      "Discussing Success & Failure",
      "Describing Festivals from Other Countries",
      "Describing Changes Over Time",
      "Giving Advice & Recommendations",
      "Describing Health & Fitness",
      "Talking About Technology & Gadgets",
      "Expressing Preferences & Reasons",
      "Making Comparisons (people, places, things)",
      "Describing Personal Achievements",
      "Handling Emergencies (in more detail)",
      "Discussing Shopping Habits",
      "Talking About Money Management",
      "Talking About News Stories",
      "Describing Problems with Public Services",
      "Writing Formal & Informal Emails",
      "Explaining Procedures (step by step)",
      "Talking About Art, Music, & Literature",
      // "Making Arrangements for Meetings",
    ],
    "B2": [
      "Second Conditional (Hypothetical Presents)",
      "Third Conditional (Hypothetical Past Outcomes)",
      "Mixed Conditionals (Time Shifts)",
      "Reported Speech: Statements & Questions",
      "Reported Speech: Reporting Verbs & Backshift",
      "Passives Across Tenses (Process vs. Result)",
      "Causatives: Have/Get Something Done",
      "Relative Clauses: Defining vs. Non-Defining",
      "Participle Clauses (Intro to Reduction)",
      "Gerunds vs. Infinitives (Preference & Purpose)",
      "Modals of Deduction (Present & Past)",
      "Modals of Obligation & Advice (Must/Have to/Should)",
      "Inversion with Negative Adverbials (Not until…)",
      "Ellipsis & Substitution in Spoken English",
      "Comparatives for Trends & Changes",
      "Linkers for Contrast & Reason (Although/Despite)",
      "Concession & Hedging (Even though/Kind of)",
      "Phrasal Verbs for Work & Projects",
      "Phrasal Verbs for Travel & Logistics",
      "Phrasal Verbs for Relationships & Emotions",
      "Collocations: Business & Productivity",
      "Collocations: Technology & Media",
      "Nuanced Vocabulary: Opinion & Evaluation",
      "Narratives: Sequencing Past Events",
      "Problem-Solving: Explaining Issues Clearly",
      "Negotiating & Reaching Agreements",
      "Making Formal Complaints & Resolutions",
      "Presentations: Signposting & Emphasis",
      "Email Tone: Neutral-Formal Requests",
      "Job Interviews: Evidence-Based Answers",
      "Data Talk: Describing Graphs & Trends",
      "Sustainability & Environment (Debate Skills)",
      "Health & Well-Being (Advice & Risk)",
      "Education & Learning (Comparing Systems)",
      "Culture & Identity (Balanced Opinions)",
      "Media Literacy: Fact vs. Opinion",
      "Technology Ethics (Pros, Cons, Trade-offs)",
      "Travel Problems & Solutions (Casework)",
      "Workplace Scenarios: Conflicts & Feedback",
      "Project Updates & Status Reports",
      "Explaining Procedures Step by Step",
      "Future in the Past (Was going to / Would)",
      "Future Forms Review (Will/Going to/Cont.)",
      "Discourse Markers for Flow (Anyway/By the way)",
      "Register: Semi-formal vs. Informal",
      "Precision with Quantifiers & Approximators",
      "Emphasis with Cleft Sentences (It is/What…)",
      "Adverbial Clauses of Time & Reason",
      "Conditionals in Polite Offers & Suggestions",
      "Exam Skills: Paraphrasing & Reformulation",
      "Fluency Clinic: Pausing & Chunking",
    ],
    "C1": [
      "Advanced Passives (Reporting/Beliefs/It is said…)",
      "Complex Noun Phrases & Nominalization",
      "Participle Clauses & Reduced Relatives",
      "Inversion for Emphasis & Style",
      "Fronting & Thematic Progression",
      "Concession & Contrast at Scale (Whereas/While)",
      "Stance & Evaluation (Apparently/Arguably)",
      "Hedging & Caution (Tend to/Relatively/Supposedly)",
      "Precision with Modality (Epistemic vs. Deontic)",
      "Subjunctive & Formulaic Formality",
      "Complex Conditionals in Reasoning",
      "Reported Speech: Nuanced Reporting Verbs",
      "Metaphor & Figurative Language in Opinion",
      "Advanced Collocations (Academic & Business)",
      "Discourse Markers for Argumentation",
      "Cohesion: Reference Chains & Substitution",
      "Ellipsis & Parallelism in Writing",
      "Paragraph Architecture & Topic Sentences",
      "Summarizing & Synthesizing Sources",
      "Counter-Arguments & Rebuttals",
      "Cause–Effect Essays (Linguistic Signalling)",
      "Problem–Solution Reports (Executive Style)",
      "Data Commentary (Charts, Tables, Infographics)",
      "Critical Reviews (Books/Films/Products)",
      "Policy Briefs: Recommendations & Risks",
      "Professional Emails: Persuasion & Politeness",
      "Meeting Skills: Chairing & Facilitation",
      "Negotiation Language: Trade-offs & Concessions",
      "Cross-Cultural Pragmatics & Politeness",
      "Register Shifts: Formal, Neutral, Informal",
      "Public Speaking: Rhetorical Devices",
      "Storytelling for Business & Advocacy",
      "Academic Integrity: Paraphrase & Citation",
      "Evaluating Evidence & Source Quality",
      "Discourse of Technology & AI Ethics",
      "Climate & Sustainability: Nuanced Debate",
      "Health Policy & Public Communication",
      "Economics & Work Futures (Gig/Remote)",
      "Media Discourses: Bias & Framing",
      "Legal & Policy Language (Plain-Englishing)",
      "Error Typology: Fossilized vs. Developmental",
      "Pronunciation: Sentence Stress & Prominence",
      "Prosody: Intonation for Attitude",
      "Fluency: Chunking & Formulaic Sequences",
      "Idiomaticity in Professional Contexts",
      "Multi-word Verbs: Nuance & Register",
      "Preposition Patterns in Academic English",
      "Complex Time & Aspect Nuances",
      "Editing for Clarity, Concision, Cohesion",
      "Exam Strategies: Synthesis & Evaluation Tasks",
    ],
    "C2": [
      "Near-Native Pragmatics: Implicature & Inference",
      "Rhetorical Precision: Framing & Reframing",
      "High-Level Stance: Nuance & Calibration",
      "Advanced Inversion & Emphatic Structures",
      "Theme–Rheme Mastery & Information Flow",
      "Dense Nominal Style vs. Plain English",
      "Metadiscourse: Guiding the Reader/Listener",
      "Irony, Understatement, and Hyperbole",
      "Register Mastery: Legal/Academic/Journalistic",
      "Genre Blending & Voice Control",
      "Intertextuality & Allusion in Argument",
      "Lexical Sophistication: Low-Frequency Items",
      "Collocation Webs & Idiomatic Precision",
      "Metaphor Clusters in Abstract Topics",
      "Evaluation Language: Gradability & Scaling",
      "Hedging vs. Boosting: Strategic Choice",
      "Argument Architecture: Macro-Structure",
      "Counterfactual Reasoning at Length",
      "Complex Conditionals in Policy & Risk",
      "Advanced Passives & Agent Suppression",
      "Clefting & Pseudo-Clefts for Focus",
      "Nominalizations in Expert Discourse",
      "Compression Techniques: Ellipsis/Deletion",
      "Rhythm & Prosody for Persuasion",
      "Pronunciation: Subtle Reduction & Linking",
      "Debate Masterclass: Refutation & Pivoting",
      "Socratic Questioning & Dialectic",
      "Forensic Language: Precision & Caution",
      "Discourse Ethics & Bias Mitigation",
      "Reasoning with Uncertainty & Probability",
      "Data-Driven Argumentation & Caveats",
      "Policy Memos & Executive Summaries",
      "Opinion Columns & Editorial Style",
      "Grant/Proposal Writing: Persuasion & Evidence",
      "Peer Review & Professional Feedback",
      "Cultural Literacy & Allusive Language",
      "Humour & Wit: Pragmatic Boundaries",
      "Crisis Communication & Reputation",
      "Strategic Storytelling for Leadership",
      "Negotiation at C-suite Level: Subtext",
      "Cross-Register Style Shifts On the Fly",
      "Global Englishes: Audience Adaptation",
      "Error-Free Control in High Stakes",
      "Editing at C2: Style, Rhythm, Voice",
      "Paraphrase without Semantic Drift",
      "Summarize vs. Synthesize vs. Critique",
      "Interpreting Ambiguity & Polysemy",
      "Ethos/Pathos/Logos: Rhetoric in Practice",
      "Exam Peak: Synthesize Multiple Sources",
      "Capstone: Long-Form Seminar Presentation",
    ],
  };

  static List<String> englishLevel = ["A1", "A2", "B1", "B2", "C1", "C2"];
}
